In [1]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."

In [2]:
A[0:5]

'안녕하세요'

In [3]:
A[-1]

'.'

In [4]:
A[-5:]

'간입니다.'

In [5]:
A[-6:-4]

'시간'

In [6]:
A[21:23]

'시간'

In [7]:
A = "당신의 영어 성적은 {}점 입니다. 그리고 수학 성적은 {}점 입니다."
A.format(90, 80)

'당신의 영어 성적은 90점 입니다. 그리고 수학 성적은 80점 입니다.'

In [8]:
print(("{:.2f}, {:.5f}").format(3.141592, 3.1415926535))

3.14, 3.14159


In [9]:
url = "https://www.youtube.com/"
str = url.replace("https://", "")
print(str)

www.youtube.com/


In [10]:
url = "https://www.youtube.com/"
str = url.replace("youtube", "naver")
print(str)

https://www.naver.com/


In [11]:
A = ["독고영재, 50", "김철수, 30"]
type(A[0])

str

In [12]:
A[0][:4]

'독고영재'

In [13]:
a = "독고영재, 50"
b = "김철수, 30"

In [14]:
a.index(",")

4

In [15]:
a[:a.index(",")]

'독고영재'

In [16]:
b[:b.index(",")]

'김철수'

In [17]:
a = ["독고영재, 50", "김철수, 30"]
b = ["김철수, 20", "김영희, 25"]

In [18]:
a[0][:a[0].index(",")]

'독고영재'

In [19]:
b[1][:b[1].index(",")]

'김영희'

In [20]:
a = ["hi", 10, "80", "김철수", 50, 50.6]
a.append(50)

In [21]:
a

['hi', 10, '80', '김철수', 50, 50.6, 50]

In [22]:
a.pop(1)

10

In [23]:
a.index(50)

3

In [24]:
b = a.index("80")
a.pop(b)

'80'

In [25]:
a

['hi', '김철수', 50, 50.6, 50]

In [26]:
import numpy as np

In [27]:
a = np.array([1, 2, 3, 4])
a = np.append(a, [4, 5])

In [28]:
a

array([1, 2, 3, 4, 4, 5])

In [29]:
a = np.insert(a, 1, [7, 8])

In [30]:
a

array([1, 7, 8, 2, 3, 4, 4, 5])

In [37]:
a = np.array([1, 2, 3, 4, 5])

In [33]:
a = np.delete(a, [1, 3])

In [34]:
a

array([1, 3, 5])

In [38]:
a[a <= 4]

array([1, 2, 3, 4])

In [39]:
a[a != 4]

array([1, 2, 3, 5])

In [40]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [42]:
merged_array = np.vstack((array1, array2))
print(merged_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [43]:
merged_array = np.hstack((array1, array2))
print(merged_array)

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
A = {1 : "김철수", 20 : "박영희"}

In [45]:
A[1]

'김철수'

In [50]:
A[2]

KeyError: 2

In [51]:
A[20]

'박영희'

In [52]:
A.get(1)

'김철수'

In [53]:
A.get(2)

In [56]:
A={"1-A" : "김철수", "20-B" : "박영희"}
A["2-A"] = "영재"
del A["20-B"]

In [57]:
A

{'1-A': '김철수', '2-A': '영재'}

In [58]:
A = {
    "1-A" : [1, 2, 3, 4, 5],
    "20-B" : ["A", "B", "C", "D", "E"]
}

In [59]:
A

{'1-A': [1, 2, 3, 4, 5], '20-B': ['A', 'B', 'C', 'D', 'E']}

In [19]:
import numpy as np

In [12]:
A = [10, 20, 30, [1, 2, 3]]
A[3]     

[1, 2, 3]

In [13]:
math = [20, 30, 40, 50, 60]
eng = [50, 70, 50, 60, 90]

In [17]:
C1 = "https://www.youtube.com/"
C2 = C1.replace("https://", "")
C3 = C2.replace("youtube", "naver")
C4 = C3.replace("/", "")
print(C4)

www.naver.com


In [25]:
math1 = ((int(math[0]) + int(math[1]) + int(math[2]) + int(math[3]) + int(math[4]))
         // 5)
math1

40

In [21]:
D = np.array([1, 2, 100, 4, 5, 900])
D = np.delete(D, [2, -1])
D

array([1, 2, 4, 5])

In [22]:
E = {
    "math" : [20, 30, 40, 50, 60],
    "eng" : [50, 70, 50, 60, 90]
}

In [24]:
(E["math"][0]) + (E["eng"][2])

70